#!/usr/bin/env python
"""Generate docs/models.md — params + FLOPs (+ I/O shape, tier) for every bundled preset.

Run from the repo root:  python scripts/model_table.py
FLOPs = 2 x MACs, counted over Conv2d + Linear at each preset's declared input size
(`model.img_h/img_w`); BN/activation/elementwise ops are ignored (negligible).
"""
from __future__ import annotations

import glob
import os
import sys

import torch
import torch.nn as nn
import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_DIR = os.path.join(REPO, "src", "opndet", "configs")
OUT = os.path.join(REPO, "docs", "models.md")


def _count_macs(model: nn.Module) -> int:
    macs = [0]
    hooks = []

    def hk(mod, _inp, out):
        if isinstance(mod, nn.Conv2d):
            o = out[0] if isinstance(out, (tuple, list)) else out
            macs[0] += (o.shape[-2] * o.shape[-1] * mod.out_channels
                        * (mod.in_channels // mod.groups) * mod.kernel_size[0] * mod.kernel_size[1])
        elif isinstance(mod, nn.Linear):
            macs[0] += mod.in_features * mod.out_features

    for m in model.modules():
        if isinstance(m, (nn.Conv2d, nn.Linear)):
            hooks.append(m.register_forward_hook(hk))
    ic, h, w = model.input_shape
    model.eval()
    with torch.no_grad():
        out = model(torch.zeros(1, ic, h, w))
    for hh in hooks:
        hh.remove()
    if isinstance(out, dict):
        t = out.get("output", next(iter(out.values())))
    else:
        t = out
    out_shape = tuple(t.shape)
    return macs[0], (ic, h, w), out_shape


def main() -> int:
    sys.path.insert(0, os.path.join(REPO, "src"))
    from opndet.yaml_build import build_model_from_yaml  # noqa: E402

    rows = []
    for path in sorted(glob.glob(os.path.join(CONFIG_DIR, "*.yaml"))):
        name = os.path.basename(path).replace("opndet-", "").replace(".yaml", "")
        try:
            with open(path) as f:
                tier = ((yaml.safe_load(f) or {}).get("model", {}) or {}).get("tier", "edge")
            m = build_model_from_yaml(path)
            params = sum(p.numel() for p in m.parameters())
            macs, in_shape, out_shape = _count_macs(m)
            rows.append((name, params, macs, in_shape, out_shape, tier))
        except Exception as e:  # noqa: BLE001 — non-model yamls (e.g. train.yaml) just get skipped
            print(f"skip {name}: {type(e).__name__}: {e}", file=sys.stderr)

    rows.sort(key=lambda r: (r[1], r[0]))
    lines = [
        "# Bundled model presets — params & FLOPs",
        "",
        "Auto-generated by `scripts/model_table.py` — **don't hand-edit**; re-run it after adding/changing a preset.",
        "FLOPs = 2 × MACs over Conv2d + Linear at the preset's declared input size (`model.img_h/img_w` in the YAML).",
        "",
        "| Preset | Params | GFLOPs | Input (C×H×W) | Output | Tier |",
        "|--------|-------:|-------:|---------------|--------|------|",
    ]
    for name, params, macs, (ic, h, w), out_shape, tier in rows:
        p = f"{params/1e6:.3f}M" if params >= 1e5 else f"{params/1e3:.0f}K"
        lines.append(f"| `{name}` | {p} | {2*macs/1e9:.2f} | {ic}×{h}×{w} | `{list(out_shape)}` | {tier} |")
    lines.append("")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({len(rows)} presets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
